networks:
  deploy-guide-dev:
    driver: bridge

services:
  nextpizza.api:
    container_name: next-pizza
    image: ${DOCKER_REGISTRY-}nextpizzaapi
    build:
      context: .
      dockerfile: NextPizza.API/Dockerfile
    ports:
      - "80:80"
    networks:
      - deploy-guide-dev
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: nextpizza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres312
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    networks:
      - deploy-guide-dev
    
      
volumes:
  postgres-data:
